### ISSUE TITLE
Start Button implementation on Quiz page

### ISSUE THREAD

**Issue by nashbrowns** [nashbrowns/GifVia#5]
I'd like to implement a start button on the quiz html page. 

Currently, the timer starts and questions are loaded immediately as the page is loaded. I would rather have a button the user can press to begin the quiz before things get populated.

**Comment by KrystalCW** [comment]
Hey Nash! I developed this functionality -- let's make sure HTML/logic match to be able to execute it

**Comment by nashbrowns** [comment]
Thanks Crystal! I put a div in place on my side. We'll put it all together
in class today
