### ISSUE TITLE
Quiz currently runs indefinitely

### ISSUE THREAD

**Issue by nashbrowns** [nashbrowns/GifVia#7]
There is no end to the quiz at this point, it just loads questions forever. I think we were capping it at 10 questions?

**Comment by philliqmakris** [comment]
I think maybe after 10 questions it should ask the user if they want to continue for 10 more, since on my high score page we left a space for "# of questions answered"

**Comment by KrystalCW** [comment]
This has been fixed -- there is both the option to choose a new topic which takes the user back to index.html or load another "12" questions (set to 3 right now for testing purposes)
